// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq10E71ODSxMs2QXdHv69LjjqxwI5Q9VQ',
    appId: '1:104432303063:web:1289811a580c2f82bfa992',
    messagingSenderId: '104432303063',
    projectId: 'loginandregister-f057b',
    authDomain: 'loginandregister-f057b.firebaseapp.com',
    storageBucket: 'loginandregister-f057b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_M4SR8dXnuUcaO1zXdnL1ozFXovtrrc',
    appId: '1:104432303063:android:23759f3a983fc5b7bfa992',
    messagingSenderId: '104432303063',
    projectId: 'loginandregister-f057b',
    storageBucket: 'loginandregister-f057b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKvrI05IcddXPxD1CBGRec92h_HEG0U9c',
    appId: '1:104432303063:ios:f6691b79bbf03ec1bfa992',
    messagingSenderId: '104432303063',
    projectId: 'loginandregister-f057b',
    storageBucket: 'loginandregister-f057b.appspot.com',
    iosBundleId: 'com.example.jobspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKvrI05IcddXPxD1CBGRec92h_HEG0U9c',
    appId: '1:104432303063:ios:903f17cbf08097edbfa992',
    messagingSenderId: '104432303063',
    projectId: 'loginandregister-f057b',
    storageBucket: 'loginandregister-f057b.appspot.com',
    iosBundleId: 'com.example.jobspot.RunnerTests',
  );
}
